name: tracker
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^8.1.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  equatable: ^2.0.5

  # Screenshots
  screenshot: ^3.0.0

  # File operations
  path_provider: ^2.1.1
  path: ^1.8.3

  # Database
  sqflite_common_ffi: ^2.3.0
  sqflite: ^2.3.0

  # Activity monitoring (Windows/Linux/macOS)
  win32: ^5.0.7  # For Windows
  ffi: ^2.1.0

  # UI
  cupertino_icons: ^1.0.2
  intl: ^0.19.0


dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
